In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import pylab as pl
import seaborn as sns
from fitter import Fitter, get_common_distributions, get_distributions

In [3]:
df = pd.read_csv('train.csv')
pd.set_option('display.max_columns', None)
df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,6,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,14,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,14,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,3,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,3,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,5,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,16,483,754,3919,19,4,2,1,1,1,3

In [4]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [5]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [6]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
X = mms.fit_transform(X)

In [7]:
X

array([[0.22778891, 0.        , 0.68      , ..., 0.        , 0.        ,
        1.        ],
       [0.34736139, 1.        , 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.04141617, 1.        , 0.        , ..., 1.        , 1.        ,
        0.        ],
       ...,
       [0.94188377, 0.        , 0.16      , ..., 1.        , 1.        ,
        0.        ],
       [0.6753507 , 0.        , 0.16      , ..., 1.        , 1.        ,
        1.        ],
       [0.00601202, 1.        , 0.6       , ..., 1.        , 1.        ,
        1.        ]])

In [8]:
y

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [9]:
y = pd.get_dummies(y)
y

      0  1  2  3
0     0  1  0  0
1     0  0  1  0
2     0  0  1  0
3     0  0  1  0
4     0  1  0  0
...  .. .. .. ..
1995  1  0  0  0
1996  0  0  1  0
1997  0  0  0  1
1998  1  0  0  0
1999  0  0  0  1

[2000 rows x 4 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=3)

In [11]:
y_train.shape

(1500, 4)

In [33]:
model = tf.keras.models.Sequential(
[
    tf.keras.layers.Dense(20 , activation='relu' , input_shape=(20,)),
    tf.keras.layers.Dense(100 , activation='relu'),
    tf.keras.layers.Dense(20 , activation='relu'),
    tf.keras.layers.Dense(4 , activation='softmax')    
])

In [34]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001) , loss = tf.keras.losses.CategoricalCrossentropy() , metrics=[tf.keras.metrics.CategoricalAccuracy()])

In [ ]:
model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test), batch_size=24)

Epoch 1/100
63/63 [==============================] - 2s 13ms/step - loss: 1.3737 - categorical_accuracy: 0.2867 - val_loss: 1.3480 - val_categorical_accuracy: 0.3300
Epoch 2/100
63/63 [==============================] - 0s 6ms/step - loss: 1.3005 - categorical_accuracy: 0.3733 - val_loss: 1.2547 - val_categorical_accuracy: 0.4140
Epoch 3/100
63/63 [==============================] - 0s 6ms/step - loss: 1.1411 - categorical_accuracy: 0.4760 - val_loss: 1.0124 - val_categorical_accuracy: 0.5780
Epoch 4/100
63/63 [==============================] - 0s 7ms/step - loss: 0.9108 - categorical_accuracy: 0.6220 - val_loss: 0.7802 - val_categorical_accuracy: 0.6960
Epoch 5/100
63/63 [==============================] - 1s 9ms/step - loss: 0.6835 - categorical_accuracy: 0.7287 - val_loss: 0.5732 - val_categorical_accuracy: 0.8120
Epoch 6/100
63/63 [==============================] - 0s 7ms/step - loss: 0.5276 - categorical_accuracy: 0.7953 - val_loss: 0.4733 - val_categorical_accuracy: 0.8260
Epoch 7/100
63/63 [==============================] - 0s 7ms/step - loss: 0.4377 - categorical_accuracy: 0.8320 - val_loss: 0.3999 - val_categorical_accuracy: 0.8440
Epoch 8/100
63/63 [==============================] - 0s 7ms/step - loss: 0.3752 - categorical_accuracy: 0.8627 - val_loss: 0.3373 - val_categorical_accuracy: 0.8780
Epoch 9/100
63/63 [==============================] - 1s 8ms/step - loss: 0.3316 - categorical_accuracy: 0.8780 - val_loss: 0.3115 - val_categorical_accuracy: 0.8740
Epoch 10/100
63/63 [==============================] - 0s 8ms/step - loss: 0.2899 - categorical_accuracy: 0.8880 - val_loss: 0.2755 - val_categorical_accuracy: 0.9000
Epoch 11/100
63/63 [==============================] - 0s 7ms/step - loss: 0.2735 - categorical_accuracy: 0.8873 - val_loss: 0.2908 - val_categorical_accuracy: 0.8740
Epoch 12/100
63/63 [==============================] - 1s 8ms/step - loss: 0.2553 - categorical_accuracy: 0.8960 - val_loss: 0.2328 - val_categorical_accuracy: 0.9020
Epoch 13/100
63/63 [==============================] - 1s 10ms/step - loss: 0.2327 - categorical_accuracy: 0.9100 - val_loss: 0.2215 - val_categorical_accuracy: 0.9140
Epoch 14/100
63/63 [==============================] - 0s 7ms/step - loss: 0.2129 - categorical_accuracy: 0.9173 - val_loss: 0.2107 - val_categorical_accuracy: 0.9220
Epoch 15/100
63/63 [==============================] - 0s 7ms/step - loss: 0.2225 - categorical_accuracy: 0.9033 - val_loss: 0.2291 - val_categorical_accuracy: 0.9040
Epoch 16/100
63/63 [==============================] - 0s 7ms/step - loss: 0.1901 - categorical_accuracy: 0.9273 - val_loss: 0.2006 - val_categorical_accuracy: 0.9140
Epoch 17/100
63/63 [==============================] - 0s 6ms/step - loss: 0.1985 - categorical_accuracy: 0.9200 - val_loss: 0.2079 - val_categorical_accuracy: 0.9100
Epoch 18/100
63/63 [==============================] - 0s 6ms/step - loss: 0.1728 - categorical_accuracy: 0.9387 - val_loss: 0.1844 - val_categorical_accuracy: 0.9220
Epoch 19/100
63/63 [==============================] - 1s 8ms/step - loss: 0.1642 - categorical_accuracy: 0.9360 - val_loss: 0.2712 - val_categorical_accuracy: 0.8720
Epoch 20/100
63/63 [==============================] - 1s 9ms/step - loss: 0.1650 - categorical_accuracy: 0.9367 - val_loss: 0.1777 - val_categorical_accuracy: 0.9120
Epoch 21/100
63/63 [==============================] - 1s 8ms/step - loss: 0.1748 - categorical_accuracy: 0.9300 - val_loss: 0.1671 - val_categorical_accuracy: 0.9180
Epoch 22/100
63/63 [==============================] - 1s 10ms/step - loss: 0.1672 - categorical_accuracy: 0.9327 - val_loss: 0.1510 - val_categorical_accuracy: 0.9420
Epoch 23/100
63/63 [==============================] - 0s 7ms/step - loss: 0.1517 - categorical_accuracy: 0.9447 - val_loss: 0.1542 - val_categorical_accuracy: 0.9340
Epoch 24/100
63/63 [==============================] - 1s 10ms/step - loss: 0.1322 - categorical_accuracy: 0.9573 - val_loss: 0.1551 - val_categorical_accuracy: 0.9400
Epoch 25/100
63/63 [==============================] - 1s 9ms/step - loss: 0.1300 - categorical_accuracy: 0.9480 - val_loss: 0.1421 - val_categorical_accuracy: 0.9460
Epoch 26/100
63/63 [==============================] - 0s 7ms/step - loss: 0.1290 - categorical_accuracy: 0.9533 - val_loss: 0.1387 - val_categorical_accuracy: 0.9400
Epoch 27/100
63/63 [==============================] - 1s 9ms/step - loss: 0.1375 - categorical_accuracy: 0.9467 - val_loss: 0.1385 - val_categorical_accuracy: 0.9340
Epoch 28/100
63/63 [==============================] - 1s 9ms/step - loss: 0.1166 - categorical_accuracy: 0.9633 - val_loss: 0.1341 - val_categorical_accuracy: 0.9460
Epoch 29/100
63/63 [==============================] - 0s 7ms/step - loss: 0.1239 - categorical_accuracy: 0.9567 - val_loss: 0.1586 - val_categorical_accuracy: 0.9300
Epoch 30/100
63/63 [==============================] - 0s 7ms/step - loss: 0.1222 - categorical_accuracy: 0.9527 - val_loss: 0.1382 - val_categorical_accuracy: 0.9400
Epoch 31/100
63/63 [==============================] - 0s 6ms/step - loss: 0.1072 - categorical_accuracy: 0.9640 - val_loss: 0.1213 - val_categorical_accuracy: 0.9540
Epoch 32/100
63/63 [==============================] - 0s 6ms/step - loss: 0.1033 - categorical_accuracy: 0.9673 - val_loss: 0.1209 - val_categorical_accuracy: 0.9520
Epoch 33/100
63/63 [==============================] - 1s 11ms/step - loss: 0.1258 - categorical_accuracy: 0.9493 - val_loss: 0.1375 - val_categorical_accuracy: 0.9460
Epoch 34/100
63/63 [==============================] - 1s 9ms/step - loss: 0.0986 - categorical_accuracy: 0.9700 - val_loss: 0.1335 - val_categorical_accuracy: 0.9440
Epoch 35/100
52/63 [=======================>......] - ETA: 0s - loss: 0.0992 - categorical_accuracy: 0.9720